import { ConvexError } from "convex/values"; import type {Doc,Id} from "./_generated/dataModel"; import type {MutationCtx,QueryCtx} from "./_generated/server"; import {capabilities,defaultRoleCapabilities,type Capability} from "../src/lib/permissions";
type Ctx=MutationCtx|QueryCtx;
export async function currentUser(ctx:Ctx){const identity=await ctx.auth.getUserIdentity(); if(!identity) throw new ConvexError("Please sign in."); const user=await ctx.db.query("appUsers").withIndex("by_subject",q=>q.eq("clerkSubject",identity.tokenIdentifier)).unique(); if(!user) throw new ConvexError("Your profile is still syncing. Refresh in a moment."); return {identity,user};}
export async function requireMembership(ctx:Ctx,companyId:Id<"companies">){const {user}=await currentUser(ctx); const company=await ctx.db.get(companyId); if(!company||company.deletedAt) throw new ConvexError("Company not found."); const membership=await ctx.db.query("companyMemberships").withIndex("by_company_user",q=>q.eq("companyId",companyId).eq("userId",user._id)).unique(); if(!membership||!membership.active) throw new ConvexError("You do not have access to this company."); return {user,membership,company};}
export async function membershipCapabilities(ctx:Ctx,m:Doc<"companyMemberships">){const allowed=new Set<Capability>(defaultRoleCapabilities[m.role]); const overrides=await ctx.db.query("permissionOverrides").withIndex("by_membership",q=>q.eq("membershipId",m._id)).collect(); for(const o of overrides){if(!capabilities.includes(o.capability as Capability)) continue; o.effect==="allow"?allowed.add(o.capability as Capability):allowed.delete(o.capability as Capability)} return allowed;}
export async function requireCapability(ctx:Ctx,companyId:Id<"companies">,capability:Capability){const auth=await requireMembership(ctx,companyId); const caps=await membershipCapabilities(ctx,auth.membership); if(!caps.has(capability)) throw new ConvexError("You do not have access to do that."); return {...auth,capabilities:caps};}
async function addActiveMembership(ctx:Ctx,ids:Set<Id<"companyMemberships">>,companyId:Id<"companies">,id:Id<"companyMemberships">){const candidate=await ctx.db.get(id); if(candidate?.companyId===companyId&&candidate.active) ids.add(id);}
export async function scopedMembershipIds(ctx:Ctx,companyId:Id<"companies">,m:Doc<"companyMemberships">){if(m.role==="Admin"){const all=await ctx.db.query("companyMemberships").withIndex("by_company",q=>q.eq("companyId",companyId)).collect(); return new Set(all.filter(x=>x.active).map(x=>x._id));} if(m.role==="Employee") return new Set<Id<"companyMemberships">>([m._id]); const ids=new Set<Id<"companyMemberships">>([m._id]); const scope=await ctx.db.query("managerScopes").withIndex("by_manager",q=>q.eq("managerMembershipId",m._id)).unique(); if(!scope) return ids; for(const id of scope.userMembershipIds) await addActiveMembership(ctx,ids,companyId,id); for(const b of scope.branchIds){const as=await ctx.db.query("userBranchAssignments").withIndex("by_branch",q=>q.eq("branchId",b)).collect(); for(const a of as) await addActiveMembership(ctx,ids,companyId,a.membershipId)} for(const d of scope.departmentIds){const as=await ctx.db.query("userDepartmentAssignments").withIndex("by_department",q=>q.eq("departmentId",d)).collect(); for(const a of as) await addActiveMembership(ctx,ids,companyId,a.membershipId)} return ids;}
export async function assertCanAssign(ctx:Ctx,companyId:Id<"companies">,m:Doc<"companyMemberships">,assignees:Id<"companyMemberships">[],kind:"jd"|"one_time"){const caps=await membershipCapabilities(ctx,m); const prefix=kind==="jd"?"tasks:jd":"tasks:one_time"; if(caps.has(`${prefix}:assign:any` as Capability)) return; if(caps.has(`${prefix}:assign:managed` as Capability)){const scoped=await scopedMembershipIds(ctx,companyId,m); if(assignees.every(id=>scoped.has(id))) return;} throw new ConvexError("You can only assign tasks inside your scope.");}
export async function assertCanUpdateTask(ctx:Ctx,companyId:Id<"companies">,m:Doc<"companyMemberships">,assignees:Id<"companyMemberships">[],kind:"jd"|"one_time"){const caps=await membershipCapabilities(ctx,m); const prefix=kind==="jd"?"tasks:jd":"tasks:one_time"; if(caps.has(`${prefix}:update:any` as Capability)) return; if(caps.has(`${prefix}:update:managed` as Capability)){const scoped=await scopedMembershipIds(ctx,companyId,m); if(assignees.every(id=>scoped.has(id))) return;} if(caps.has(`${prefix}:update:self` as Capability)&&assignees.every(id=>id===m._id)) return; throw new ConvexError("You cannot update this task.");}
export async function visibleSop(ctx:Ctx,companyId:Id<"companies">,m:Doc<"companyMemberships">,sop:Doc<"sops">){if(sop.companyId!==companyId) return false; if(sop.scopeType==="company"||m.role==="Admin") return true; if(sop.scopeType==="user") return sop.userMembershipIds.includes(m._id); if(sop.scopeType==="branch"){const rows=await ctx.db.query("userBranchAssignments").withIndex("by_membership",q=>q.eq("membershipId",m._id)).collect(); return rows.some(a=>sop.branchIds.includes(a.branchId));} const rows=await ctx.db.query("userDepartmentAssignments").withIndex("by_membership",q=>q.eq("membershipId",m._id)).collect(); return rows.some(a=>sop.departmentIds.includes(a.departmentId));}
export function assertPlatformAdminEmail(email?:string|null){const configured=process.env.PLATFORM_ADMIN_EMAIL?.toLowerCase(); if(!configured||email?.toLowerCase()!==configured) throw new ConvexError("You do not have access to this.");}
