import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const role = v.union(v.literal("Admin"), v.literal("Manager"), v.literal("Employee"));
const priority = v.union(v.literal("low"), v.literal("medium"), v.literal("high"));
const rec = v.union(v.literal("daily"), v.literal("every_other_day"), v.literal("weekly"), v.literal("monthly"), v.literal("semiannually"), v.literal("annually"));
const taskStatus = v.union(v.literal("due"), v.literal("in_progress"), v.literal("completed"));
const scope = v.union(v.literal("company"), v.literal("branch"), v.literal("department"), v.literal("user"));
const taskType = v.union(v.literal("jd"), v.literal("one_time"));

export default defineSchema({
  appUsers: defineTable({ clerkSubject: v.string(), email: v.string(), firstName: v.string(), secondName: v.optional(v.string()), imageUrl: v.optional(v.string()), createdAt: v.number(), updatedAt: v.number() }).index("by_subject", ["clerkSubject"]).index("by_email", ["email"]),
  companies: defineTable({ name: v.string(), timeZone: v.optional(v.string()), createdAt: v.number(), createdBy: v.optional(v.id("appUsers")), deletedAt: v.optional(v.number()) }).index("by_deleted", ["deletedAt"]),
  companyMemberships: defineTable({ companyId: v.id("companies"), userId: v.id("appUsers"), role, active: v.boolean(), createdAt: v.number(), updatedAt: v.number() }).index("by_company", ["companyId"]).index("by_user", ["userId"]).index("by_company_user", ["companyId", "userId"]),
  branches: defineTable({ companyId: v.id("companies"), name: v.string(), order: v.optional(v.number()), createdAt: v.number(), updatedAt: v.number() }).index("by_company", ["companyId"]),
  departments: defineTable({ companyId: v.id("companies"), branchId: v.id("branches"), name: v.string(), order: v.optional(v.number()), createdAt: v.number(), updatedAt: v.number() }).index("by_company", ["companyId"]).index("by_branch", ["branchId"]),
  userBranchAssignments: defineTable({ companyId: v.id("companies"), membershipId: v.id("companyMemberships"), branchId: v.id("branches") }).index("by_membership", ["membershipId"]).index("by_branch", ["branchId"]),
  userDepartmentAssignments: defineTable({ companyId: v.id("companies"), membershipId: v.id("companyMemberships"), departmentId: v.id("departments") }).index("by_membership", ["membershipId"]).index("by_department", ["departmentId"]),
  managerBranchScopes: defineTable({ companyId: v.id("companies"), managerMembershipId: v.id("companyMemberships"), branchId: v.id("branches"), updatedAt: v.number() }).index("by_manager", ["managerMembershipId"]).index("by_branch", ["branchId"]).index("by_company", ["companyId"]),
  managerDepartmentScopes: defineTable({ companyId: v.id("companies"), managerMembershipId: v.id("companyMemberships"), departmentId: v.id("departments"), updatedAt: v.number() }).index("by_manager", ["managerMembershipId"]).index("by_department", ["departmentId"]).index("by_company", ["companyId"]),
  managerUserScopes: defineTable({ companyId: v.id("companies"), managerMembershipId: v.id("companyMemberships"), userMembershipId: v.id("companyMemberships"), updatedAt: v.number() }).index("by_manager", ["managerMembershipId"]).index("by_user", ["userMembershipId"]).index("by_company", ["companyId"]),
  permissionOverrides: defineTable({ companyId: v.id("companies"), membershipId: v.id("companyMemberships"), capability: v.string(), effect: v.union(v.literal("allow"), v.literal("deny")), updatedAt: v.number() }).index("by_membership", ["membershipId"]),
  invitations: defineTable({ companyId: v.id("companies"), email: v.string(), role, branchIds: v.optional(v.array(v.id("branches"))), departmentIds: v.optional(v.array(v.id("departments"))), managedBranchIds: v.optional(v.array(v.id("branches"))), managedDepartmentIds: v.optional(v.array(v.id("departments"))), managedUserMembershipIds: v.optional(v.array(v.id("companyMemberships"))), permissionOverrides: v.optional(v.array(v.object({ capability: v.string(), effect: v.union(v.literal("allow"), v.literal("deny")) }))), token: v.string(), status: v.union(v.literal("pending"), v.literal("accepted"), v.literal("revoked")), invitedBy: v.optional(v.id("appUsers")), createdAt: v.number(), expiresAt: v.number(), sentAt: v.optional(v.number()) }).index("by_company", ["companyId"]).index("by_token", ["token"]).index("by_email", ["email"]),
  jdTasks: defineTable({ companyId: v.id("companies"), title: v.string(), description: v.optional(v.string()), time: v.optional(v.string()), quantity: v.optional(v.number()), recurrence: rec, cycleStartedAt: v.number(), status: taskStatus, statusCycleStart: v.optional(v.number()), overdueAt: v.optional(v.number()), assigneeMembershipIds: v.array(v.id("companyMemberships")), createdByMembershipId: v.id("companyMemberships"), createdAt: v.number(), updatedAt: v.number() }).index("by_company", ["companyId"]),
  jdTaskCompletions: defineTable({ companyId: v.id("companies"), jdTaskId: v.id("jdTasks"), cycleStart: v.number(), completedByMembershipId: v.id("companyMemberships"), completedAt: v.number(), note: v.optional(v.string()) }).index("by_task", ["jdTaskId"]).index("by_task_and_cycleStart", ["jdTaskId", "cycleStart"]).index("by_task_and_completedAt", ["jdTaskId", "completedAt"]),
  jdTaskCycleRecords: defineTable({ companyId: v.id("companies"), jdTaskId: v.id("jdTasks"), cycleStart: v.number(), cycleEnd: v.number(), status: v.literal("missed"), recordedAt: v.number() }).index("by_company", ["companyId"]).index("by_task", ["jdTaskId"]).index("by_task_and_cycleStart", ["jdTaskId", "cycleStart"]),
  oneTimeTasks: defineTable({ companyId: v.id("companies"), title: v.string(), description: v.optional(v.string()), dueDate: v.optional(v.number()), time: v.optional(v.string()), quantity: v.optional(v.number()), assigneeMembershipIds: v.array(v.id("companyMemberships")), createdByMembershipId: v.id("companyMemberships"), priority, status: taskStatus, overdueAt: v.optional(v.number()), completedAt: v.optional(v.number()), completedByMembershipId: v.optional(v.id("companyMemberships")), createdAt: v.number(), updatedAt: v.number() }).index("by_company", ["companyId"]),
  taskComments: defineTable({ companyId: v.id("companies"), taskType, taskId: v.string(), authorMembershipId: v.id("companyMemberships"), body: v.string(), createdAt: v.number() }).index("by_task", ["taskType", "taskId"]).index("by_company", ["companyId"]),
  taskAttachments: defineTable({ companyId: v.id("companies"), taskType, taskId: v.string(), fileName: v.string(), contentType: v.string(), size: v.number(), storageId: v.id("_storage"), createdByMembershipId: v.id("companyMemberships"), createdAt: v.number() }).index("by_task", ["taskType", "taskId"]).index("by_company", ["companyId"]),
  sops: defineTable({ companyId: v.id("companies"), title: v.string(), content: v.string(), scopeType: scope, creatorMembershipId: v.id("companyMemberships"), updatedByMembershipId: v.id("companyMemberships"), createdAt: v.number(), updatedAt: v.number() }).index("by_company", ["companyId"]),
  sopBranchScopes: defineTable({ companyId: v.id("companies"), sopId: v.id("sops"), branchId: v.id("branches") }).index("by_sop", ["sopId"]).index("by_branch", ["branchId"]).index("by_company", ["companyId"]),
  sopDepartmentScopes: defineTable({ companyId: v.id("companies"), sopId: v.id("sops"), departmentId: v.id("departments") }).index("by_sop", ["sopId"]).index("by_department", ["departmentId"]).index("by_company", ["companyId"]),
  sopUserScopes: defineTable({ companyId: v.id("companies"), sopId: v.id("sops"), userMembershipId: v.id("companyMemberships") }).index("by_sop", ["sopId"]).index("by_user", ["userMembershipId"]).index("by_company", ["companyId"]),
  sopEmbeddings: defineTable({ companyId: v.id("companies"), sopId: v.id("sops"), chunk: v.string(), embedding: v.array(v.number()), metadata: v.object({ title: v.string(), scopeType: scope }), updatedAt: v.number() }).index("by_sop", ["sopId"]).index("by_company", ["companyId"]).vectorIndex("by_embedding", { vectorField: "embedding", dimensions: 1024, filterFields: ["companyId"] }),
  auditEvents: defineTable({ companyId: v.optional(v.id("companies")), actorUserId: v.optional(v.id("appUsers")), actorEmail: v.optional(v.string()), action: v.string(), targetType: v.string(), targetId: v.optional(v.string()), metadata: v.optional(v.any()), createdAt: v.number() }).index("by_company", ["companyId"]),
  aiChatSessions: defineTable({ companyId: v.id("companies"), membershipId: v.id("companyMemberships"), title: v.optional(v.string()), hasMessages: v.optional(v.boolean()), modelTier: v.optional(v.union(v.literal("flash"), v.literal("pro"))), proProvider: v.optional(v.union(v.literal("deepseek"), v.literal("kimi"))), createdAt: v.number(), updatedAt: v.number() }).index("by_membership", ["membershipId"]).index("by_membership_and_updatedAt", ["membershipId", "updatedAt"]).index("by_company", ["companyId"]),
  aiChatMessages: defineTable({ sessionId: v.id("aiChatSessions"), role: v.union(v.literal("user"), v.literal("assistant"), v.literal("tool")), content: v.string(), clientMessageId: v.optional(v.string()), createdAt: v.number() }).index("by_session", ["sessionId"]).index("by_session_and_clientMessageId", ["sessionId", "clientMessageId"]),
  aiRateLimits: defineTable({ key: v.string(), count: v.number(), resetAt: v.number(), updatedAt: v.number() }).index("by_key", ["key"]).index("by_resetAt", ["resetAt"]),
});
