import { defineSchema, defineTable } from "convex/server"; import { v } from "convex/values";
const role=v.union(v.literal("Admin"),v.literal("Manager"),v.literal("Employee")); const priority=v.union(v.literal("low"),v.literal("medium"),v.literal("high")); const rec=v.union(v.literal("daily"),v.literal("every_other_day"),v.literal("weekly"),v.literal("every_two_weeks"),v.literal("monthly"),v.literal("semiannually"),v.literal("annually")); const scope=v.union(v.literal("company"),v.literal("branch"),v.literal("department"),v.literal("user"));
export default defineSchema({
 appUsers:defineTable({clerkSubject:v.string(),email:v.string(),name:v.optional(v.string()),imageUrl:v.optional(v.string()),createdAt:v.number(),updatedAt:v.number()}).index("by_subject",["clerkSubject"]).index("by_email",["email"]),
 companies:defineTable({name:v.string(),createdAt:v.number(),createdBy:v.optional(v.id("appUsers")),deletedAt:v.optional(v.number())}).index("by_deleted",["deletedAt"]),
 companyMemberships:defineTable({companyId:v.id("companies"),userId:v.id("appUsers"),role,active:v.boolean(),createdAt:v.number(),updatedAt:v.number()}).index("by_company",["companyId"]).index("by_user",["userId"]).index("by_company_user",["companyId","userId"]),
 branches:defineTable({companyId:v.id("companies"),name:v.string(),createdAt:v.number(),updatedAt:v.number()}).index("by_company",["companyId"]),
 departments:defineTable({companyId:v.id("companies"),branchId:v.id("branches"),name:v.string(),createdAt:v.number(),updatedAt:v.number()}).index("by_company",["companyId"]).index("by_branch",["branchId"]),
 userBranchAssignments:defineTable({companyId:v.id("companies"),membershipId:v.id("companyMemberships"),branchId:v.id("branches")}).index("by_membership",["membershipId"]).index("by_branch",["branchId"]),
 userDepartmentAssignments:defineTable({companyId:v.id("companies"),membershipId:v.id("companyMemberships"),departmentId:v.id("departments")}).index("by_membership",["membershipId"]).index("by_department",["departmentId"]),
 managerScopes:defineTable({companyId:v.id("companies"),managerMembershipId:v.id("companyMemberships"),branchIds:v.array(v.id("branches")),departmentIds:v.array(v.id("departments")),userMembershipIds:v.array(v.id("companyMemberships")),updatedAt:v.number()}).index("by_manager",["managerMembershipId"]),
 permissionOverrides:defineTable({companyId:v.id("companies"),membershipId:v.id("companyMemberships"),capability:v.string(),effect:v.union(v.literal("allow"),v.literal("deny")),updatedAt:v.number()}).index("by_membership",["membershipId"]),
 invitations:defineTable({companyId:v.id("companies"),email:v.string(),role,token:v.string(),status:v.union(v.literal("pending"),v.literal("accepted"),v.literal("revoked")),invitedBy:v.optional(v.id("appUsers")),createdAt:v.number(),expiresAt:v.number(),sentAt:v.optional(v.number())}).index("by_company",["companyId"]).index("by_token",["token"]),
 jdTasks:defineTable({companyId:v.id("companies"),title:v.string(),description:v.optional(v.string()),time:v.optional(v.string()),count:v.optional(v.number()),recurrence:rec,startDate:v.number(),assigneeMembershipIds:v.array(v.id("companyMemberships")),createdByMembershipId:v.id("companyMemberships"),priority,createdAt:v.number(),updatedAt:v.number()}).index("by_company",["companyId"]),
 jdTaskCompletions:defineTable({companyId:v.id("companies"),jdTaskId:v.id("jdTasks"),cycleStart:v.number(),completedByMembershipId:v.id("companyMemberships"),completedAt:v.number(),note:v.optional(v.string())}).index("by_task",["jdTaskId"]),
 oneTimeTasks:defineTable({companyId:v.id("companies"),title:v.string(),description:v.optional(v.string()),dueDate:v.number(),assigneeMembershipIds:v.array(v.id("companyMemberships")),createdByMembershipId:v.id("companyMemberships"),priority,completedAt:v.optional(v.number()),completedByMembershipId:v.optional(v.id("companyMemberships")),createdAt:v.number(),updatedAt:v.number()}).index("by_company",["companyId"]),
 taskComments:defineTable({companyId:v.id("companies"),taskType:v.union(v.literal("jd"),v.literal("one_time")),taskId:v.string(),authorMembershipId:v.id("companyMemberships"),body:v.string(),createdAt:v.number()}).index("by_task",["taskType","taskId"]),
 taskAttachments:defineTable({companyId:v.id("companies"),taskType:v.union(v.literal("jd"),v.literal("one_time")),taskId:v.string(),fileName:v.string(),contentType:v.string(),size:v.number(),storageId:v.optional(v.id("_storage")),createdByMembershipId:v.id("companyMemberships"),createdAt:v.number()}).index("by_task",["taskType","taskId"]),
 sops:defineTable({companyId:v.id("companies"),title:v.string(),content:v.string(),scopeType:scope,branchIds:v.array(v.id("branches")),departmentIds:v.array(v.id("departments")),userMembershipIds:v.array(v.id("companyMemberships")),creatorMembershipId:v.id("companyMemberships"),updatedByMembershipId:v.id("companyMemberships"),createdAt:v.number(),updatedAt:v.number()}).index("by_company",["companyId"]),
 sopEmbeddings:defineTable({companyId:v.id("companies"),sopId:v.id("sops"),chunk:v.string(),embedding:v.array(v.number()),metadata:v.object({title:v.string(),scopeType:scope}),updatedAt:v.number()}).index("by_sop",["sopId"]).index("by_company",["companyId"]),
 auditEvents:defineTable({companyId:v.optional(v.id("companies")),actorUserId:v.optional(v.id("appUsers")),actorEmail:v.optional(v.string()),action:v.string(),targetType:v.string(),targetId:v.optional(v.string()),metadata:v.optional(v.any()),createdAt:v.number()}).index("by_company",["companyId"]),
 aiChatSessions:defineTable({companyId:v.id("companies"),membershipId:v.id("companyMemberships"),title:v.optional(v.string()),createdAt:v.number(),updatedAt:v.number()}).index("by_membership",["membershipId"]),
 aiChatMessages:defineTable({sessionId:v.id("aiChatSessions"),role:v.union(v.literal("user"),v.literal("assistant"),v.literal("tool")),content:v.string(),createdAt:v.number()}).index("by_session",["sessionId"]),
});
