import { ConvexError, v } from "convex/values";
import { action, mutation, query } from "./_generated/server";
import { api } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { requireCapability, requireMembership, visibleSop } from "./permissions";

async function assertTargets(ctx: any, companyId: Id<"companies">, args: { branchIds: Id<"branches">[]; departmentIds: Id<"departments">[]; userMembershipIds: Id<"companyMemberships">[] }) {
  for (const branchId of args.branchIds) { const branch = await ctx.db.get(branchId); if (!branch || branch.companyId !== companyId) throw new ConvexError("Branch not found."); }
  for (const departmentId of args.departmentIds) { const department = await ctx.db.get(departmentId); if (!department || department.companyId !== companyId) throw new ConvexError("Department not found."); }
  for (const membershipId of args.userMembershipIds) { const membership = await ctx.db.get(membershipId); if (!membership || membership.companyId !== companyId) throw new ConvexError("User not found."); }
}
function manageCapability(scopeType: "company" | "branch" | "department" | "user") { return scopeType === "company" ? "sops:manage:company" : scopeType === "branch" ? "sops:manage:branch" : scopeType === "department" ? "sops:manage:department" : "sops:manage:user"; }

export const list = query({ args: { companyId: v.id("companies"), search: v.optional(v.string()) }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const rows = await ctx.db.query("sops").withIndex("by_company", (q) => q.eq("companyId", args.companyId)).collect(); const out = []; const search = args.search?.toLowerCase(); for (const sop of rows) { if (await visibleSop(ctx, args.companyId, membership, sop)) { if (!search || sop.title.toLowerCase().includes(search) || sop.content.toLowerCase().includes(search)) out.push(sop); } } return out; } });
export const get = query({ args: { companyId: v.id("companies"), sopId: v.id("sops") }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const sop = await ctx.db.get(args.sopId); if (!sop || sop.companyId !== args.companyId || !(await visibleSop(ctx, args.companyId, membership, sop))) throw new ConvexError("SOP not found."); return sop; } });
export const create = mutation({ args: { companyId: v.id("companies"), title: v.string(), content: v.string(), scopeType: v.union(v.literal("company"), v.literal("branch"), v.literal("department"), v.literal("user")), branchIds: v.array(v.id("branches")), departmentIds: v.array(v.id("departments")), userMembershipIds: v.array(v.id("companyMemberships")) }, handler: async (ctx, args) => { const cap = manageCapability(args.scopeType); const { membership } = await requireCapability(ctx, args.companyId, cap); await assertTargets(ctx, args.companyId, args); const now = Date.now(); return await ctx.db.insert("sops", { ...args, title: args.title.trim(), creatorMembershipId: membership._id, updatedByMembershipId: membership._id, createdAt: now, updatedAt: now }); } });
export const update = mutation({ args: { companyId: v.id("companies"), sopId: v.id("sops"), title: v.string(), content: v.string() }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const sop = await ctx.db.get(args.sopId); if (!sop || sop.companyId !== args.companyId || !(await visibleSop(ctx, args.companyId, membership, sop))) throw new ConvexError("SOP not found."); await requireCapability(ctx, args.companyId, manageCapability(sop.scopeType)); await ctx.db.patch(args.sopId, { title: args.title.trim(), content: args.content, updatedByMembershipId: membership._id, updatedAt: Date.now() }); } });
export const remove = mutation({ args: { companyId: v.id("companies"), sopId: v.id("sops") }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const sop = await ctx.db.get(args.sopId); if (!sop || sop.companyId !== args.companyId || !(await visibleSop(ctx, args.companyId, membership, sop))) throw new ConvexError("SOP not found."); await requireCapability(ctx, args.companyId, manageCapability(sop.scopeType)); await ctx.db.delete(args.sopId); } });
export const searchAccessible = query({ args: { companyId: v.id("companies"), query: v.string() }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const rows = await ctx.db.query("sops").withIndex("by_company", (q) => q.eq("companyId", args.companyId)).collect(); const needle = args.query.toLowerCase(); const out = []; for (const sop of rows) { if (await visibleSop(ctx, args.companyId, membership, sop) && (sop.title.toLowerCase().includes(needle) || sop.content.toLowerCase().includes(needle))) out.push({ id: sop._id, title: sop.title, excerpt: sop.content.slice(0, 500), scopeType: sop.scopeType }); } return out.slice(0, 8); } });
export const storeEmbedding = mutation({ args: { companyId: v.id("companies"), sopId: v.id("sops"), chunk: v.string(), embedding: v.array(v.number()), title: v.string(), scopeType: v.union(v.literal("company"), v.literal("branch"), v.literal("department"), v.literal("user")) }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const sop = await ctx.db.get(args.sopId); if (!sop || sop.companyId !== args.companyId || !(await visibleSop(ctx, args.companyId, membership, sop))) throw new ConvexError("SOP not found."); await requireCapability(ctx, args.companyId, manageCapability(sop.scopeType)); return await ctx.db.insert("sopEmbeddings", { companyId: args.companyId, sopId: args.sopId, chunk: args.chunk, embedding: args.embedding, metadata: { title: args.title, scopeType: args.scopeType }, updatedAt: Date.now() }); } });
export const indexSop = action({ args: { companyId: v.id("companies"), sopId: v.id("sops") }, handler: async (ctx, args) => { const sop = await ctx.runQuery(api.sops.get, { companyId: args.companyId, sopId: args.sopId }); const apiKey = process.env.VOYAGE_API_KEY; if (!apiKey) return { skipped: true }; const input = [sop.title + "\n\n" + sop.content]; const res = await fetch("https://api.voyageai.com/v1/embeddings", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.VOYAGE_EMBEDDING_MODEL || "voyage-4", input }) }); const json = await res.json() as { data?: { embedding: number[] }[] }; const embedding = json.data?.[0]?.embedding; if (embedding) await ctx.runMutation(api.sops.storeEmbedding, { companyId: args.companyId, sopId: args.sopId, chunk: input[0], embedding, title: sop.title, scopeType: sop.scopeType }); return { skipped: false }; } });
