import { ConvexError, v } from "convex/values";
import { mutation, query } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import { assertCanAssign, assertCanUpdateTask, membershipCapabilities, requireCapability, requireMembership, scopedMembershipIds } from "./permissions";

type Rec = Doc<"jdTasks">["recurrence"];
const day = 86_400_000;
function sod(ms: number) { const d = new Date(ms); d.setHours(0, 0, 0, 0); return d.getTime(); }
function addM(ms: number, m: number) { const d = new Date(ms); d.setMonth(d.getMonth() + m); return d.getTime(); }
function next(s: number, r: Rec) {
  switch (r) {
    case "daily": return s + day;
    case "every_other_day": return s + 2 * day;
    case "weekly": return s + 7 * day;
    case "every_two_weeks": return s + 14 * day;
    case "monthly": return addM(s, 1);
    case "semiannually": return addM(s, 6);
    case "annually": return addM(s, 12);
  }
}
function cycle(startDate: number, r: Rec, now = Date.now()) { let start = sod(startDate); let end = next(start, r); while (end <= now) { start = end; end = next(start, r); } return { start, end }; }
function prevCycle(startDate: number, r: Rec) { const c = cycle(startDate, r); let prev = sod(startDate); let end = next(prev, r); while (end < c.start) { prev = end; end = next(prev, r); } return c.start === sod(startDate) ? null : { start: prev, end: c.start }; }
async function enrich(ctx: any, ids: Id<"companyMemberships">[]) { const rows = []; for (const id of ids) { const membership = await ctx.db.get(id); const user = membership ? await ctx.db.get(membership.userId) : null; if (membership && user) rows.push({ membership: { _id: membership._id, role: membership.role }, user: { name: user.name, email: user.email } }); } return rows; }
async function visible(ctx: any, companyId: Id<"companies">, m: Doc<"companyMemberships">, assignees: Id<"companyMemberships">[]) { const scoped = await scopedMembershipIds(ctx, companyId, m); return assignees.some((id) => scoped.has(id)); }
async function assertAssigneesInCompany(ctx: any, companyId: Id<"companies">, assignees: Id<"companyMemberships">[]) { if (!assignees.length) throw new ConvexError("At least one assignee is required."); for (const id of assignees) { const membership = await ctx.db.get(id); if (!membership || membership.companyId !== companyId || !membership.active) throw new ConvexError("Assignee not found in this company."); } }
async function jdState(ctx: any, t: Doc<"jdTasks">) { const c = cycle(t.startDate, t.recurrence); const p = prevCycle(t.startDate, t.recurrence); const completions = await ctx.db.query("jdTaskCompletions").withIndex("by_task", (q: any) => q.eq("jdTaskId", t._id)).collect(); const currentDone = completions.some((x: Doc<"jdTaskCompletions">) => x.cycleStart === c.start); const prevMissed = !!p && !completions.some((x: Doc<"jdTaskCompletions">) => x.cycleStart === p.start); return { status: currentDone ? "Done" : prevMissed ? "Overdue" : "Due", currentCycleStart: c.start, currentCycleEnd: c.end, dueAt: c.end, lastCompletedAt: completions.sort((a: any, b: any) => b.completedAt - a.completedAt)[0]?.completedAt ?? null }; }
function oneState(t: Doc<"oneTimeTasks">) { if (t.completedAt) return "Done"; if (t.dueDate < Date.now()) return "Overdue"; if (sod(t.dueDate) === sod(Date.now())) return "Due today"; return "Upcoming"; }

export const listJd = query({ args: { companyId: v.id("companies") }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const tasks = await ctx.db.query("jdTasks").withIndex("by_company", (q) => q.eq("companyId", args.companyId)).collect(); const out = []; for (const t of tasks) if (await visible(ctx, args.companyId, membership, t.assigneeMembershipIds)) out.push({ ...t, state: await jdState(ctx, t), assignees: await enrich(ctx, t.assigneeMembershipIds) }); return out; } });
export const getJd = query({ args: { companyId: v.id("companies"), taskId: v.id("jdTasks") }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const t = await ctx.db.get(args.taskId); if (!t || t.companyId !== args.companyId || !(await visible(ctx, args.companyId, membership, t.assigneeMembershipIds))) throw new ConvexError("Task not found."); const comments = await ctx.db.query("taskComments").withIndex("by_task", (q) => q.eq("taskType", "jd").eq("taskId", args.taskId)).collect(); const attachments = await ctx.db.query("taskAttachments").withIndex("by_task", (q) => q.eq("taskType", "jd").eq("taskId", args.taskId)).collect(); return { task: { ...t, state: await jdState(ctx, t), assignees: await enrich(ctx, t.assigneeMembershipIds) }, comments, attachments }; } });
export const createJd = mutation({ args: { companyId: v.id("companies"), title: v.string(), description: v.optional(v.string()), time: v.optional(v.string()), count: v.optional(v.number()), recurrence: v.union(v.literal("daily"), v.literal("every_other_day"), v.literal("weekly"), v.literal("every_two_weeks"), v.literal("monthly"), v.literal("semiannually"), v.literal("annually")), startDate: v.number(), assigneeMembershipIds: v.array(v.id("companyMemberships")), priority: v.union(v.literal("low"), v.literal("medium"), v.literal("high")) }, handler: async (ctx, args) => { const { membership, user } = await requireCapability(ctx, args.companyId, "tasks:jd:create"); const title = args.title.trim(); if (!title) throw new ConvexError("Title is required."); await assertAssigneesInCompany(ctx, args.companyId, args.assigneeMembershipIds); await assertCanAssign(ctx, args.companyId, membership, args.assigneeMembershipIds, "jd"); const now = Date.now(); const id = await ctx.db.insert("jdTasks", { ...args, title, createdByMembershipId: membership._id, createdAt: now, updatedAt: now }); await ctx.db.insert("auditEvents", { companyId: args.companyId, actorUserId: user._id, action: "jd_task.create", targetType: "jdTask", targetId: id, createdAt: now }); return id; } });
export const completeJd = mutation({ args: { companyId: v.id("companies"), taskId: v.id("jdTasks"), note: v.optional(v.string()) }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const t = await ctx.db.get(args.taskId); if (!t || t.companyId !== args.companyId) throw new ConvexError("Task not found."); await assertCanUpdateTask(ctx, args.companyId, membership, t.assigneeMembershipIds, "jd"); const c = cycle(t.startDate, t.recurrence); const existing = await ctx.db.query("jdTaskCompletions").withIndex("by_task", (q) => q.eq("jdTaskId", args.taskId)).collect(); if (existing.some((x) => x.cycleStart === c.start)) return null; return await ctx.db.insert("jdTaskCompletions", { companyId: args.companyId, jdTaskId: args.taskId, cycleStart: c.start, completedByMembershipId: membership._id, completedAt: Date.now(), note: args.note }); } });

export const listOneTime = query({ args: { companyId: v.id("companies") }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const tasks = await ctx.db.query("oneTimeTasks").withIndex("by_company", (q) => q.eq("companyId", args.companyId)).collect(); const out = []; for (const t of tasks) if (await visible(ctx, args.companyId, membership, t.assigneeMembershipIds)) out.push({ ...t, state: oneState(t), assignees: await enrich(ctx, t.assigneeMembershipIds) }); return out; } });
export const getOneTime = query({ args: { companyId: v.id("companies"), taskId: v.id("oneTimeTasks") }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const t = await ctx.db.get(args.taskId); if (!t || t.companyId !== args.companyId || !(await visible(ctx, args.companyId, membership, t.assigneeMembershipIds))) throw new ConvexError("Task not found."); const comments = await ctx.db.query("taskComments").withIndex("by_task", (q) => q.eq("taskType", "one_time").eq("taskId", args.taskId)).collect(); const attachments = await ctx.db.query("taskAttachments").withIndex("by_task", (q) => q.eq("taskType", "one_time").eq("taskId", args.taskId)).collect(); return { task: { ...t, state: oneState(t), assignees: await enrich(ctx, t.assigneeMembershipIds) }, comments, attachments }; } });
export const createOneTime = mutation({ args: { companyId: v.id("companies"), title: v.string(), description: v.optional(v.string()), dueDate: v.number(), assigneeMembershipIds: v.array(v.id("companyMemberships")), priority: v.union(v.literal("low"), v.literal("medium"), v.literal("high")) }, handler: async (ctx, args) => { const { membership, user } = await requireCapability(ctx, args.companyId, "tasks:one_time:create"); const title = args.title.trim(); if (!title) throw new ConvexError("Title is required."); await assertAssigneesInCompany(ctx, args.companyId, args.assigneeMembershipIds); await assertCanAssign(ctx, args.companyId, membership, args.assigneeMembershipIds, "one_time"); const now = Date.now(); const id = await ctx.db.insert("oneTimeTasks", { ...args, title, createdByMembershipId: membership._id, createdAt: now, updatedAt: now }); await ctx.db.insert("auditEvents", { companyId: args.companyId, actorUserId: user._id, action: "one_time_task.create", targetType: "oneTimeTask", targetId: id, createdAt: now }); return id; } });
export const completeOneTime = mutation({ args: { companyId: v.id("companies"), taskId: v.id("oneTimeTasks") }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const t = await ctx.db.get(args.taskId); if (!t || t.companyId !== args.companyId) throw new ConvexError("Task not found."); await assertCanUpdateTask(ctx, args.companyId, membership, t.assigneeMembershipIds, "one_time"); await ctx.db.patch(args.taskId, { completedAt: Date.now(), completedByMembershipId: membership._id, updatedAt: Date.now() }); } });
export const addComment = mutation({ args: { companyId: v.id("companies"), taskType: v.union(v.literal("jd"), v.literal("one_time")), taskId: v.string(), body: v.string() }, handler: async (ctx, args) => { const { membership } = await requireCapability(ctx, args.companyId, "tasks:comment"); const taskId = args.taskType === "jd" ? ctx.db.normalizeId("jdTasks", args.taskId) : ctx.db.normalizeId("oneTimeTasks", args.taskId); if (!taskId) throw new ConvexError("Task not found."); const t = await ctx.db.get(taskId); if (!t || t.companyId !== args.companyId || !(await visible(ctx, args.companyId, membership, t.assigneeMembershipIds))) throw new ConvexError("Task not found."); return await ctx.db.insert("taskComments", { companyId: args.companyId, taskType: args.taskType, taskId, authorMembershipId: membership._id, body: args.body.trim(), createdAt: Date.now() }); } });
export const assignableUsers = query({
  args: { companyId: v.id("companies"), kind: v.union(v.literal("jd"), v.literal("one_time")) },
  handler: async (ctx, args) => {
    const { membership } = await requireMembership(ctx, args.companyId);
    const caps = await membershipCapabilities(ctx, membership);
    const prefix = args.kind === "jd" ? "tasks:jd" : "tasks:one_time";
    if (!caps.has(`${prefix}:create` as any)) return [];
    let ids: Set<Id<"companyMemberships">>;
    if (caps.has(`${prefix}:assign:any` as any)) {
      const all = await ctx.db.query("companyMemberships").withIndex("by_company", (q) => q.eq("companyId", args.companyId)).collect();
      ids = new Set(all.filter((m) => m.active).map((m) => m._id));
    } else if (caps.has(`${prefix}:assign:managed` as any)) {
      ids = await scopedMembershipIds(ctx, args.companyId, membership);
    } else {
      ids = new Set([membership._id]);
    }
    return await enrich(ctx, Array.from(ids));
  },
});

export const accessibleTasksForAi = query({ args: { companyId: v.id("companies"), overdueOnly: v.optional(v.boolean()) }, handler: async (ctx, args) => { const { membership } = await requireMembership(ctx, args.companyId); const out: any[] = []; for (const t of await ctx.db.query("jdTasks").withIndex("by_company", (q) => q.eq("companyId", args.companyId)).collect()) { if (await visible(ctx, args.companyId, membership, t.assigneeMembershipIds)) { const s = await jdState(ctx, t); if (!args.overdueOnly || s.status === "Overdue") out.push({ type: "JD", id: t._id, title: t.title, state: s.status, dueAt: s.dueAt }); } } for (const t of await ctx.db.query("oneTimeTasks").withIndex("by_company", (q) => q.eq("companyId", args.companyId)).collect()) { if (await visible(ctx, args.companyId, membership, t.assigneeMembershipIds)) { const s = oneState(t); if (!args.overdueOnly || s === "Overdue") out.push({ type: "One-time", id: t._id, title: t.title, state: s, dueAt: t.dueDate }); } } return out; } });
